### ISSUE TITLE
clock handle and time label are not in sync all the time.

### ISSUE THREAD

**Issue by palaniraja** [andrewroycarter/TimeScroller#1]
Wonderful control to have. Thanks for your effort Andrew.

I noticed some times the clock handle and time label don't sync. Just scrolling and up and down. Since it is just a random date values, I can't be sure whether the clock or the label is wrong. 

Will do few more test and update you soon.

Check the screenshot - http://minus.com/m1s4eYbhx

**Comment by andrewroycarter** [comment]
Great, thanks for the help!

I'll make the table cells be a little less plain looking and also have them display the time, so that way it's easier to see if it's working correctly.
