### ISSUE TITLE
timeScroller won't work if rows could not full fill at least one page

### ISSUE THREAD

**Issue by flypigz** [andrewroycarter/TimeScroller#12]
Xcode: 4.3.2 
IOS SDK: ISO5.1

if the row cout is too less to fill one page of the uitableView, and the scroll indicator is not shown, the timer scroller does not work as expected. It seems that this project relies on the scroll indicator, I am not sure if this is a limitation or we can fix it...

You can simply modify this demo project and change " i >= -15" to make sure the row number is less than 10, and reproduce this issue.  e.g, today is 04.27, you can change it to "i>=20".....

 for (int i = todayComponents.day; i >= -15; i--) {

```
        NSMutableDictionary *dictionary = [NSMutableDictionary dictionary];
        [dictionary setObject:@"Title here" forKey:@"title"];

        components.year = todayComponents.year;
        components.month = todayComponents.month;
        components.day = i;
        components.hour = arc4random() % 23;
        components.minute = arc4random() % 59;

        NSDate *date = [calendar dateFromComponents:components];
        [dictionary setObject:date forKey:@"date"];

        [_datasource addObject:dictionary];

    }
```

**Comment by andrewroycarter** [comment]
Awesome,
What does path do in this case? I don't think I've ever seen it in a state without enough cells?

**Comment by flypigz** [comment]
it seems that when the row number is not enough, Path2 will return a large footer height, so the overall height of the table will exceeds one page.  I tried this use an newly created account,  the scroll indicator will always show even there is no message.

**Comment by andrewroycarter** [comment]
Good call, maybe I can add some sort of warning log that tells the user to do that if it detects that's what's happening? Do you think that'd be a good solution? I wouldn't want the scroller to inject a footer...

**Comment by flypigz** [comment]
what about adding this as an restriction/limitation to the README.md? then user will pay attention to this. I have checked some similar projects of scrollview scroller, they all depend on the scroll indicator, the same as the path2 application, that is why they enlarge the footer height to fix this. I think this is acceptable.

Thank you.

**Comment by andrewroycarter** [comment]
Good call, I'll edit it in the morning

Sent from my iPhone

On Apr 26, 2012, at 12:45 AM, flypigz
reply@reply.github.com
wrote:

**Comment by flypigz** [comment]
OK, thanks.~~~ close this comment.
