### ISSUE TITLE
Hands in the clock not moving, though the time in the text is right

### ISSUE THREAD

**Issue by Jean1Jean** [andrewroycarter/TimeScroller#13]
Hi, Thanks so much for this wonderful TimeScroller! I simply love it :-) ! 

Am using iOS 5 and Xcode 4.2. Am writing a simple app that has a simple layout : a text box and a button at the top half of the screen, and a TableView at the bottom half. As the user keeps entering the text, it keeps getting added to the table. The timer is appearing as I scroll, and the date/time is also being displayed correctly, but the hands in the clock aren't moving. Can you please help?

In the ViewController.h
@interface com_FirstViewController : UIViewController <UITableViewDelegate, UITableViewDataSource, TimeScrollerDelegate> {
...
...
TimeScroller \* _timeScroller;
....
}
...
@property (nonatomic, retain) TimeScroller \* _timeScroller;
....

In ViewController.m:
....
# import "TimeScroller.h"

....
....
....
- (void)viewDidLoad {
  
  [super viewDidLoad];
   _timeScroller = [[TimeScroller alloc] initWithDelegate:self];
  ....
  ....
  }
  ....
  ....
  ....
- (UITableView *)tableViewForTimeScroller: (TimeScroller *)timeScroller {
  NSLog(@"tableViewForTimeScroller : returned UITableView");
  return table;
  }

//The date for a given cell
- (NSDate *)dateForCell:(UITableViewCell *)cell {
  
  NSIndexPath *indexPath = [table indexPathForCell:cell];
  int timeInt = [[[arrayInput objectAtIndex:[indexPath row]] objectForKey:@"time"] intValue]; 
  NSDate *time = [Utility getIntAsDate:timeInt];
  NSLog(@"returned time for scroller: %@", time);
  return time;  
  }
- (void)scrollViewDidScroll:(UIScrollView *)scrollView {
  NSLog(@"scrollViewDidScroll");
  [_timeScroller scrollViewDidScroll];  
  }
- (void)scrollViewDidEndDecelerating:(UIScrollView *)scrollView {
  NSLog(@"scrollViewDidEndDecelerating");
  [_timeScroller scrollViewDidEndDecelerating];
  }
- (void)scrollViewWillBeginDragging:(UIScrollView *)scrollView {
  NSLog(@"scrollViewWillBeginDragging");
  [_timeScroller scrollViewWillBeginDragging];
  }
- (void)scrollViewDidEndDragging:(UIScrollView *)scrollView willDecelerate:(BOOL)decelerate {  
  NSLog(@"scrollViewDidEndDragging");
  if (!decelerate) {  
      [_timeScroller scrollViewDidEndDecelerating];  
  }  
  }

@end

**Comment by andrewroycarter** [comment]
Would you be able to post an example project that replicates this error? I'd be happy to check it out!

**Comment by andrewroycarter** [comment]
Haven't been able to reproduce this )=
If you can post a repo that shows the issue lemme know, and I'll look into it! Or maybe someone else's commit that's been accepted has resolved the issue?

**Comment by Jean1Jean** [comment]
Hi Andrew, Thanks for responding. I apologize for my delay in responding to
your email. Let me create a sample project & share with you.

Thanks

On Thu, Jun 21, 2012 at 10:17 AM, Andrew Carter <
reply@reply.github.com
