### ISSUE TITLE
device orientation support & number of rows changes

### ISSUE THREAD

**Issue by flagg19** [andrewroycarter/TimeScroller#15]
Hi.
I was having problems using TimeScroller with a tableview with few rows, that depending of device orientation may or may not fill all the tableview.

I've done some quick modification to fix this problem that may be useful to others...
I'm new to git hub, don't know if there's a better way to link the code so here two dropbox links:

https://www.dropbox.com/s/d6l9wmmq9afiohf/TimeScroller.h
https://www.dropbox.com/s/00ls8ll91ijm5qd/TimeScroller.m

This will cover the rotation problem, while for the row number changes i'm now just recreating the timeScroller every (rare) tableview reloadData.

**Comment by andrewroycarter** [comment]
Nice! If you can submit a pull request with those changes I'll get that in!

**Comment by andrewroycarter** [comment]
Closing this thanks to pull request!
