### ISSUE TITLE
Switching View Controllers causes TimeScroller to "Multiply"

### ISSUE THREAD

**Issue by bssayeda** [andrewroycarter/TimeScroller#17]
In many navigation based apps I've tested TimeScroller, if you push a new ViewController onto the navigation stack, and then navigate back to the ViewController TimeScroller will do what you see in the screenshot below, if I reinitialize the ViewController with TimeScroller in it it behaves correctly again (which is obvious since the VC is being reinitialized).

Screenshot: http://cl.ly/image/1X1A0q472D0m

I'm not sure if I'm just doing something wrong or not but I literally used the sample code verbatim.

**Comment by honkmaster** [comment]
The height of the containing view is calculated wrong and so the scroller image is multiplied. I was running into the same problem and so i fixed the height to a hard coded value.

self.frame = CGRectMake(0.0f, 0.0f, 320.0f, 31.0f);  // 31.0f is hard coded

**Comment by bssayeda** [comment]
That fixed the issue very quickly, I guess it would be best that this change is made to the posted code though?

**Comment by honkmaster** [comment]
I am not sure if it is a nice solution to fix the height. But normally it should be O.K.

**Comment by Rich2k** [comment]
This is how I fixed it too, hardcoding the height

**Comment by coreyfloyd** [comment]
@honkmaster @Rich2k  I am seeing this too. Which height are you talking about? the container table view?

**Comment by honkmaster** [comment]
We are talking about the height in the TimeScroller itself.

**Comment by coreyfloyd** [comment]
Thanks, yeah the size seemed weird. I guess it was "cleaner" to not hard code the height so that it auto adjusts to different images, but in practice that is not too terrible.

**Comment by andrewroycarter** [comment]
This should now be resolved!
