### ISSUE TITLE
resizableImageWithCapInsets works on ioS5 only

### ISSUE THREAD

**Issue by emanuelef** [andrewroycarter/TimeScroller#2]
Hi,
is there an alternative for non ios5? 
The control is really cool!

**Comment by andrewroycarter** [comment]
I'll try and make it work with iOS 4 as well!

**Comment by surfingtomchen** [comment]
Great! I like this control but I also try to run it on iOS4. i've changed the resizbleImageWithCapInsets with stretchableImageWithLeftCapWidth. and also remove the weekOfYear code. But eventually the code runs not quite smooth compare to running on iOS5.0.

It will be great if Andrew can make the code compatible to iOS 4.0, thanks!

**Comment by andrewroycarter** [comment]
I think I'm going to start moving this to iOS 5 only so we can use weak references on ARC as well. Maybe a fork for iOS 4?
