### ISSUE TITLE
Timescroller doesnt update when tableview has new rows

### ISSUE THREAD

**Issue by dreampowder** [andrewroycarter/TimeScroller#24]
Hi there, first of all, thanks very much for this wonderfull looking component. 

My problem is when i add new data to my tableview, timescroller prevents tableview to scroll to bottom and keeps the tableview on the last row of the tableviews previous size. Here are the steps to produce: 

1- Create a tableview with 20 rows, or else. 
2- Add a line of code to add "20 more lines" when the user reaches to the last cell. 
3- Scrollview is on the bottom of the screen (20th cell) and prevents tableview to scroll down  further.

**Comment by andrewroycarter** [comment]
Hi!
Sorry for the delay in getting back to you!
Can you upload an example project which will show the issue? I'd be glad to check into it and get the issue resolved!

**Comment by dreampowder** [comment]
Strange but i've modified your demo project to do the same thing and it is working :) i guess i should be focusing on my own code. 

Thanks for open sourcing this wonderful component!

i've added this code to the demo project: 

```
- (void)addData{
NSCalendar *calendar = [NSCalendar currentCalendar];
NSDateComponents *components = [[NSDateComponents alloc] init];
NSDate* today = [_datasource objectAtIndex:[_datasource count]-1];
NSDateComponents *todayComponents = [calendar components:NSYearCalendarUnit | NSMonthCalendarUnit | NSDayCalendarUnit fromDate:today];
for (int i = [todayComponents day]; i >= -15; i--)
{
    [components setYear:[todayComponents year]];
    [components setMonth:[todayComponents month]];
    [components setDay:i];
    [components setHour:arc4random() % 23];
    [components setMinute:arc4random() % 59];
    NSDate *date = [calendar dateFromComponents:components];
    [_datasource addObject:date];
}
[self.tableView reloadData];
}
```

and this one to the end of "cellForRowAtIndexPath" delegate method: 

```
if(indexPath.row==[_datasource count]-1){
    NSLog(@"Adding Data");
    [self addData];
}
```
