### ISSUE TITLE
CocoaPod release version out-of-date

### ISSUE THREAD

**Issue by tloring** [andrewroycarter/TimeScroller#25]
Love this TimeScroller, thanks for making it available! 

I was looking a an issue with _lastDate being null in -updateDisplayWithCell: which throws an error; I see that was resolved 10/29/12:

https://github.com/andrewroycarter/TimeScroller/commit/a593efe8cce1352a4d008522fd7ec326e6ab0dd7

Using CocoaPods, it has the current version of 1.2; I see a tag in the repo for 1.3, but this fix is after that 1.3 tag. Any chance for a most current release to include these fixes? 

Thanks!
Thom

**Comment by andrewroycarter** [comment]
I'll get on this now :)

**Comment by andrewroycarter** [comment]
Ok version 2.0.0 should be up soon!
I've made a few breaking changes, but it's nothing to should take more than a few minutes to fix. I've changed the structure of the project a bit, and added a prefix to the TimeScroller class.

**Comment by tloring** [comment]
Thanks Andrew! Have 2.0.0, working great!
