### ISSUE TITLE
How to add this to a uiscrollview?

### ISSUE THREAD

**Issue by veerreef** [andrewroycarter/TimeScroller#26]
Hello there any idea how to add this control to a uiscrollview instead of a uitableview?

**Comment by andrewroycarter** [comment]
Current it's pretty specialized for a table view. It know how to get the date / time to be displayed via asking for specific table cell's related dates. You could maybe take this code and alter it to ask for a date to display for a given content offset in the table! File a feature request if you like, and I may just add it!
