### ISSUE TITLE
iOS7 Support

### ISSUE THREAD

**Issue by honkmaster** [andrewroycarter/TimeScroller#28]
The method "- (void)captureTableViewAndScrollBar" returns no Scrollbar in iOS 7. Therefore this component is not working on iOS 7.

**Comment by honkmaster** [comment]
Seem that the Width of the Scrollbar has changed from 7.0f to 3.5f.

**Comment by alexsaidani** [comment]
Yeah I noticed that too, little odd. I just added this for a quick and easy fix, probably not the nicest way of doing it, but nonetheless.

float iOS7 = 7.0;
            if ([[[UIDevice currentDevice] systemVersion] floatValue] < iOS7)
            {
                if (imageView.frame.size.width == 7.0f)
                {
                    imageView.clipsToBounds = NO;
                    [imageView addSubview:self];
                    _scrollBar = imageView;
                    _savedTableViewSize = _tableView.frame.size;
                }
            }
            else if ([[[UIDevice currentDevice] systemVersion] floatValue] >= iOS7)
            {
                if (imageView.frame.size.width == 3.5f)
                {
                    imageView.clipsToBounds = NO;
                    [imageView addSubview:self];
                    _scrollBar = imageView;
                    _savedTableViewSize = _tableView.frame.size;
                }
            }

**Comment by andrewroycarter** [comment]
Good call, I'll get a patch in for this. Also on that note, I wonder if we can think of a more iOS 7 "look" for it?

**Comment by honkmaster** [comment]
I think we need a few changes:
- Simplify the clock: just a circle, markers for 12, 3, 6, 9, hands must be just a line
- No gray background, instead blur
- The view should have no rounded corners

**Comment by alexsaidani** [comment]
In my latest iPhone app Hashtrack, I've attempted to make it more ios7 like, check out the screenshot: https://www.dropbox.com/s/m2pzitnew84k284/Photo%2024-09-2013%2015%2053%2033.png
The app is available on the AppStore now: http://download.hashtrack.co

**Comment by honkmaster** [comment]
Looks good. Ideally the border would change the tint color according to the apps tint color. Can you provide the code?

**Comment by andrewroycarter** [comment]
Looks awesome @alexsaidani, and @honkmaster I love the idea of the blurred background! I'll take inspiration from both of these to make a nice redesign for a iOS 7 only version 3.0.0

I've updated the current version to 2.0.1 to support iOS 7 with the current design.

Thanks guys

**Comment by andrewroycarter** [comment]
@honkmaster using the tint color sounds like an awesome idea

**Comment by honkmaster** [comment]
Maybe it would be gread to use a "digital" instead of an "analog" clock. iOS 7 removed all the skeumorphism and i feel that an analog clock would look strange and misplaced.
