### ISSUE TITLE
Not working on iPad iOS5

### ISSUE THREAD

**Issue by pradyumnad** [andrewroycarter/TimeScroller#3]
I have setup all the things needed.
there is a problem with hitTest withEvent..
which is returning a tableview instead of UITableviewCellContentView..
Please help me with this

**Comment by chriswill0w** [comment]
After making the project arc compatible I have the following problem in this line: 

```
UIView *view = [_tableView hitTest:point withEvent:UIEventTypeTouches];
```

The problem: implicit conversion of int to uievent\* is disallowed with arc

Do you know a solution or a workaround for the problem?

**Comment by chriswill0w** [comment]
it is a compiler error so i cannot even start the project

**Comment by pradyumnad** [comment]
@ltblueberry0  did you get it working in iOS5 ??

**Comment by chriswill0w** [comment]
I got it working on iOS5 :-). My solution:
-First convert the project to ARC: that means basically get rid off all the memory management stuff in the code of the timscroller like releases etc.
-then in the UITableView where you want to use the timescroller use custom cells instead of the standard ones
-in your custom cell class override the following method as follows:

```
 -(void)touchesBegan:(NSSet *)touches withEvent:(UIEvent *)event{
    [[NSNotificationCenter defaultCenter] 
    postNotificationName:@"touchEventFromCell" object:event];
    [super touchesBegan:touches withEvent:event];
 }
```

-in the init method of the timescroller you have to add the following now:

```
           [[NSNotificationCenter defaultCenter] 
     addObserver:self
     selector:@selector(touchEventFromCell:)
     name:@"touchEventFromCell" 
     object:nil];
```

-and the following method has to be added to the timescroller class:

```
  - (void)touchEventFromCell:(NSNotification *)notification {
UIEvent * event = ((UIEvent *) notification.object);
currentEvent = event; 
 }
```

-currentevent is a property of timescroller that you can use in the following line of code:

```
            UIView *view = [_tableView hitTest:point withEvent:currentEvent];
```

-with the above code you get an event to use for the hittest since UIEventTypeTouches cannot be used with ARC. It is maybe not a nice solution but it works and performance is still the same.

If I forgot something or if you have questions feel free to ask me
Cheers

**Comment by pradyumnad** [comment]
@ltblueberry0  when I am trying to convert to ARC I got an error which you got 
 implicit conversion of int to uievent\* is disallowed with arc

**Comment by chriswill0w** [comment]
just convert it manually remove all the memory management stuff like autoreleases, releases and so on. then comment out this line

```
   UIView *view = [_tableView hitTest:point withEvent:UIEventTypeTouches];
```

afterwards you should be able to convert it with xcode. then uncomment the above line and follow my steps I mentioned above.

**Comment by chriswill0w** [comment]
what  you could also do is. create a new ARC project in xcode. copy the timescroller classes into that project. then it will give you compiler errors in the timescroller classes where you have to remove the memory management stuff.

**Comment by pradyumnad** [comment]
@ltblueberry0  Thanks for solving the problem dude..

**Comment by chriswill0w** [comment]
no problem. you are welcome.

**Comment by pradyumnad** [comment]
@ltblueberry0  I dont know what is the reason behind this but lemme explain you the scenario.

I have 2 view controllers and in each I have a tableview.

TimeScroller is working amazing in 1st Viewcontroller
but it is not working in the second.
I debugged and printed currentEvent for both the tables and the value is "null". Can I know where is the problem.

**Comment by pradyumnad** [comment]
```
UIView *view = [_tableView hitTest:point withEvent:currentEvent];
```

I printed the "view", which turns out to be UITableView and which has to be UITableViewCellContentView

**Comment by pradyumnad** [comment]
Got the answer. 
If you need TimeScroller to be working. The Tableview we are using should be filled.
So if the number of rows does not fill in your tableviews frame the Time Scroll will not work,
FIX for that is:

resize the tableview frame with the height = number of rows \* row height;

**Comment by andrewroycarter** [comment]
Sorry for the lack of attention to the project! Looks like you guys have everything sorted out. If there is anything you'd like to merge into the project please put in a request and I'll be happy to do it!
