### ISSUE TITLE
TimeScroller is broken on iOS 8.1

### ISSUE THREAD

**Issue by MaartenZonneveld** [andrewroycarter/TimeScroller#32]
Hey!

The TimeScroller is behaving very weird on iOS 8.1. Both on the iOS 8.1 simulators and on my iPad Mini running iOS 8.1.

It's not showing at all. Except when I scroll to the top of the screen, it pops up on the bottom of the screen and goes away immediately.

When I run my app in the iOS 7.1 simulator everything works fine.
I think this problem did not occur on iOS 8.0.*, but I'm not 100% sure and I can't test that right now.

I hope this is fixable! Good luck ;)

Kind regards,
Maarten

**Comment by MaartenZonneveld** [comment]
Oh by the way, the TimeScroller is also broken in the Demo Project when running it on iOS 8.1. So I'm pretty sure it's not my code that's causing a problem.

**Comment by MaartenZonneveld** [comment]
I've added some simple NSLog's to the ACTimeScroller.m.

## iOS 7.1 output:

scrollViewDidScroll
checkChanges
Found a cell in scrollViewDidScroll. Going to update it...
updateDisplayWithCell <PFTimelineCell: (...)>

## iOS 8.1 output:

scrollViewDidScroll
checkChanges
Did not found a cell in scrollViewDidScroll! Going to fade away now...

## The code with the logs:

``` objective-c
- (void)updateDisplayWithCell:(UITableViewCell *)cell
{
    NSLog(@"updateDisplayWithCell %@", cell);
   (...)
}

- (void)scrollViewDidScroll
{
    NSLog(@"scrollViewDidScroll");

    if (!_tableView || !_scrollBar)
    {
        [self captureTableViewAndScrollBar];
    }

    [self checkChanges];

    if (!_scrollBar)
    {
        return;
    }

    CGRect selfFrame = self.frame;
    CGRect scrollBarFrame = _scrollBar.frame;

    self.frame = CGRectMake(CGRectGetWidth(selfFrame) * -1.0f,
                            (CGRectGetHeight(scrollBarFrame) / 2.0f) - (CGRectGetHeight(selfFrame) / 2.0f),
                            CGRectGetWidth(selfFrame),
                            CGRectGetHeight(_backgroundView.frame));

    CGPoint point = CGPointMake(CGRectGetMidX(self.frame), CGRectGetMidY(self.frame));
    point = [_scrollBar convertPoint:point toView:_tableView];

    UITableViewCell* cell=[_tableView cellForRowAtIndexPath:[_tableView indexPathForRowAtPoint:point]];
    if (cell) {
        NSLog(@"Found a cell in scrollViewDidScroll. Going to update it...");
        [self updateDisplayWithCell:cell];
        if (![self alpha])
        {
            [UIView animateWithDuration:0.2f delay:0.0f options:UIViewAnimationOptionCurveEaseOut animations:^{
                [self setAlpha:1.0f];
            } completion:nil];
        }
    }
    else
    {
        NSLog(@"Did not found a cell in scrollViewDidScroll! Going to fade away now...");
        if ([self alpha])
        {
            [UIView animateWithDuration:0.2f delay:0.0f options:UIViewAnimationOptionCurveEaseOut animations:^{
                [self setAlpha:0.0f];
            } completion:nil];
        }
    }
}

- (void)checkChanges
{
    NSLog(@"checkChanges");
    (...)
}
```

**Comment by whuu** [comment]
This could be fixed easily, just add:

```
  || imageView.frame.size.width == 2.5f
```

  to if statement in captureTableViewAndScrollBar method in ACTimeScroller class

The line should look this way:

```
  if (imageView.frame.size.width == 7.0f || imageView.frame.size.width == 5.0f || imageView.frame.size.width == 3.5f || imageView.frame.size.width == 2.5f)
```

**Comment by andrewroycarter** [comment]
Hey guys!
I've had github notifications turned off for a good while (I'm subscribed to so many darn projects at work) so I've missed these issues coming up.

I'll go through this project and do some cleanup over the next few days. Thanks for the interest!

**Comment by williamko** [comment]
TimeScroller works on all of the device simulators except the iPhone 6 plus. Let me know if there is a quick fix!

Thanks Andrew!

**Comment by ghost** [comment]
Any progress on this? I'm having the same issue as williamko.
